### ISSUE TITLE
Add tooltip to 'add multiple fields'

### ISSUE THREAD

**Issue by TheDenSter** [anzwdev/al-code-outline#208]
First of all, You've created some GREAT functions. I use them all the time and they are making me so much more productive.

Could you add the tooltip to the "Add multiple fields" function please, for pages and page extensions? It's very easy to add them later, thanks to another great function, but both the PTE and AppSource cops complain when they are not there.

**Comment by anzwdev** [comment]
That's a good idea, I will add it.

**Comment by anzwdev** [comment]
Just a small update. I am still working on this issue. It looks like a small change, but because of some missing features in the core of my extension I have to redesign it and change a lot inside. I am in the middle of this process and I still need a few days of work to finish it.

**Comment by anzwdev** [comment]
I've released a new version of the extension, it is now possible to add tooltips to page fields created by page/page extension wizards and 'Add multiple fields' command. You can turn it on and off by using "Create Tooltips" checkbox on wizards or by chaning value of the "alOutline.addToolTipsToPageFields" setting for 'Add multiple fields' command.

**Comment by TheDenSter** [comment]
That's great, I happened to catch the extension reload, and saw the new checkbox in the wizard. Thanks for adding that :)

**Comment by jbakach** [comment]
Hello,

I think that because of this change, the function of Add multiple fields has been broken. I cannot add new fields anymore with the new version 3.0.0. With the latest version it works well, i rolled back and it seems to be a problem with the new version 3.0.0. It is really useful, could you please take a look at it?

Thanks!!!

**Comment by anzwdev** [comment]
Hi @jbakach 

Are you using the latest version of the Microsoft AL Extension from the Visual Studio Marketplace? My extension supports the lates version of that extension from the VS Code marketplace and Nav 2018 version installed from VSIX file. If you older BC version of the Microsoft extension, some functions might not work.

**Comment by jbakach** [comment]
> Hi @jbakach
> 
> Are you using the latest version of the Microsoft AL Extension from the Visual Studio Marketplace? My extension supports the lates version of that extension from the VS Code marketplace and Nav 2018 version installed from VSIX file. If you older BC version of the Microsoft extension, some functions might not work.

Yes, sure. 

AL Language: v7.1.441584
AZ AL Dev Tools/AL Code Outline: v3.01

I have updated to the newer version and it still doesn't work. Once I roll back to version 2.0.25 it works well.

Also to mention, I have tried your cool function Create Related Tables. And it creates all the related definition tableextensions pretty well. Only one thing that doesn't create are the fields :).

Thanks for your work on this. Your extension is really helpful!

Best regards,

jbakach
