### ISSUE TITLE
"Add multiple fields" does not open fields list

### ISSUE THREAD

**Issue by Ponch18** [anzwdev/al-code-outline#254]
![image](https://user-images.githubusercontent.com/51646978/122237168-66944300-cebf-11eb-9302-6ead92a4f400.png)

This action does not work from 2.0.25 version.
It appear on pages e pageextentions but clicking on it doesn't open fields list.

**Comment by anzwdev** [comment]
Are you using the latest version of my extension? Can you see any errors if you run "AZ AL Dev Tools: Open AZ AL Dev Tools log file" command?

**Comment by Ponch18** [comment]
Yes, I've installed version 3.0.6 and log file is empty after trying to click "Add multiple fields" action.

**Comment by Ponch18** [comment]
Sorry, last version that works for me is 2.0.24 and not 2.0.25

**Comment by anzwdev** [comment]
I was trying to replicate your issue, but it works without any problems for me. Are you using the latest version of Microsoft AL Extension from Visual Studio Marketplace or another one installed from VSIX file from BC or NAV2018 installation files/docker container?

**Comment by anzwdev** [comment]
I've released a new version of the extension, could you check if it works for you now?

**Comment by StefanMaron** [comment]
I currently have the same issue, Version is v3.0.11. 

If it would help we could maybe have a quick call on discord later and I can show you

**Comment by anzwdev** [comment]
Hi @StefanMaron 

Yes, it would be nice to see how to replicate the issue. We can have a discord call or if you want, you can send me a few screenshots/short video. If your list of fields is empty, then probably my extension crashes when it parses one of your files. Can you still use page wizard to select tables and then fields after 'Add multiple fields' stops working or is everything broken?

**Comment by NKarolak** [comment]
The issue still exists in v3.0.13 on VS Code 1.59.1.
The bulb appears, but a list won't open.

**Comment by anzwdev** [comment]
Hi @NKarolak 

Is it the only broken functionality? Can you view symbols from *.app files or run page wizard and select tables and fields there? I've released a new version of the extension with a few improvements to error handling and app files loading. Could you check if it is still broken? If it does not work, could you run "Open AZ AL Dev Tools log file" command and check if there is anything in the log file?

**Comment by NKarolak** [comment]
Hi Andrzej,

the symbols explorer still works.

However, the Wizards do not:
![image](https://user-images.githubusercontent.com/34504100/132166847-5dc12f33-59b1-4431-9265-944c5f9e8062.png)
No matter what I enter, no table can be found. Hence on the next Wizard page, the field list is empty.

There's only the very same log entry as [here](https://github.com/anzwdev/al-code-outline/issues/271#issuecomment-913356128).

**Comment by anzwdev** [comment]
Thank you @NKarolak for your help. It helped me to find and fix the bug. New version of the extension is available in the vscode marketplace.

**Comment by NKarolak** [comment]
Confirmed: all mentioned issues are fixed now. Thanks Andrzej :-)
